#!/usr/bin/env node

/**
 * APK编译脚本
 * 功能：
 * 1. 切换到Android目录
 * 2. 执行Gradle构建命令
 * 3. 处理签名（Release版本）
 * 4. 复制APK到输出目录
 */

// 加载环境变量
require('dotenv').config();

const fs = require('fs');
const path = require('path');
const os = require('os');
const { execSync } = require('child_process');

const config = require('../build.config.js');

// 获取Gradle wrapper命令（跨平台支持）
function getGradleCommand() {
  const isWindows = os.platform() === 'win32';
  return isWindows ? 'gradlew.bat' : './gradlew';
}

console.log('📱 开始编译APK...\n');

// 验证Android项目存在
function validateAndroidProject() {
  const androidDir = path.join(__dirname, '..', 'android');
  
  if (!fs.existsSync(androidDir)) {
    throw new Error('Android目录不存在，请先运行 npm run init');
  }
  
  const buildGradlePath = path.join(androidDir, 'build.gradle');
  if (!fs.existsSync(buildGradlePath)) {
    throw new Error('Android项目不完整，请先运行 npm run sync');
  }
  
  console.log('✅ Android项目验证通过');
}

// 配置Android SDK路径到local.properties
function configureLocalProperties() {
  const androidDir = path.join(__dirname, '..', 'android');
  const localPropertiesPath = path.join(androidDir, 'local.properties');
  
  // 查找Android SDK路径
  let sdkPath = process.env.ANDROID_HOME || process.env.ANDROID_SDK_ROOT;
  
  if (!sdkPath) {
    // 尝试常见的Android SDK位置
    const possibleSdkPaths = [
      path.join(os.homedir(), 'AppData', 'Local', 'Android', 'Sdk'), // Windows默认位置
      path.join(os.homedir(), 'Library', 'Android', 'sdk'), // macOS默认位置
      path.join(os.homedir(), 'Android', 'Sdk'), // Linux默认位置
      'C:\\Users\\' + os.userInfo().username + '\\AppData\\Local\\Android\\Sdk', // Windows完整路径
    ];
    
    for (const possiblePath of possibleSdkPaths) {
      if (fs.existsSync(possiblePath) && fs.existsSync(path.join(possiblePath, 'platform-tools'))) {
        sdkPath = possiblePath;
        console.log(`📦 自动检测到Android SDK: ${sdkPath}`);
        break;
      }
    }
  }
  
  if (!sdkPath) {
    console.warn('⚠️  警告: 未找到Android SDK路径');
    console.warn('   请设置ANDROID_HOME环境变量，或手动编辑 android/local.properties');
    return;
  }
  
  // 验证SDK路径
  if (!fs.existsSync(path.join(sdkPath, 'platform-tools'))) {
    console.warn(`⚠️  警告: Android SDK路径无效: ${sdkPath}`);
    return;
  }
  
  // 写入local.properties文件
  // Windows路径需要转义反斜杠
  const escapedSdkPath = sdkPath.replace(/\\/g, '\\\\');
  
  const localPropertiesContent = `## This file is automatically generated by the build script.
## It contains the Android SDK location.
## Do not modify this file manually.

sdk.dir=${escapedSdkPath}
`;
  
  fs.writeFileSync(localPropertiesPath, localPropertiesContent);
  console.log(`✅ 已配置Android SDK路径: ${sdkPath}`);
}

// 检查Android SDK环境
function checkAndroidSDK() {
  try {
    // 检查ANDROID_HOME环境变量
    const androidHome = process.env.ANDROID_HOME || process.env.ANDROID_SDK_ROOT;
    if (!androidHome) {
      console.warn('⚠️  警告: 未设置ANDROID_HOME环境变量');
      console.warn('   请设置ANDROID_HOME指向Android SDK路径');
    } else {
      console.log(`✅ Android SDK路径: ${androidHome}`);
    }
    
    // 检查Java环境
    let javaHome = process.env.JAVA_HOME;
    let javaFound = false;
    
    // 验证JAVA_HOME路径是否存在
    if (javaHome) {
      const javaExe = path.join(javaHome, 'bin', os.platform() === 'win32' ? 'java.exe' : 'java');
      if (!fs.existsSync(javaExe)) {
        console.warn(`⚠️  JAVA_HOME路径无效: ${javaHome}`);
        console.warn('   尝试自动检测Java环境...');
        javaHome = null; // 重置，让脚本自动检测
      }
    }
    
    // 如果JAVA_HOME未设置或无效，尝试自动检测
    if (!javaHome) {
      const possibleJavaPaths = [];
      
      // macOS: 使用 /usr/libexec/java_home 命令检测
      if (os.platform() === 'darwin') {
        try {
          const detectedJavaHome = execSync('/usr/libexec/java_home', {
            stdio: 'pipe',
            encoding: 'utf8'
          }).trim();
          if (detectedJavaHome && fs.existsSync(detectedJavaHome)) {
            possibleJavaPaths.push(detectedJavaHome);
          }
        } catch (error) {
          // /usr/libexec/java_home 不可用，继续尝试其他路径
        }
        
        // macOS: Android Studio 自带的 JDK
        possibleJavaPaths.push(
          '/Applications/Android Studio.app/Contents/jbr',
          path.join(os.homedir(), 'Library', 'Android', 'sdk', 'jbr')
        );
      }
      
      // Windows: Android Studio 自带的 JDK
      if (os.platform() === 'win32') {
        possibleJavaPaths.push(
          'C:\\Program Files\\Android\\Android Studio\\jbr',
          'C:\\Program Files (x86)\\Android\\Android Studio\\jbr',
          path.join(os.homedir(), 'AppData', 'Local', 'Android', 'Sdk', 'jbr')
        );
      }
      
      // Linux: 常见 JDK 路径
      if (os.platform() === 'linux') {
        possibleJavaPaths.push(
          '/usr/lib/jvm/java-17-openjdk',
          '/usr/lib/jvm/java-11-openjdk',
          '/usr/lib/jvm/default-java'
        );
      }
      
      // 遍历可能的路径
      for (const javaPath of possibleJavaPaths) {
        const javaExe = path.join(javaPath, 'bin', os.platform() === 'win32' ? 'java.exe' : 'java');
        if (fs.existsSync(javaExe)) {
          javaHome = javaPath;
          console.log(`📦 自动检测到Java SDK: ${javaHome}`);
          // 临时设置JAVA_HOME（仅当前进程）
          process.env.JAVA_HOME = javaHome;
          break;
        }
      }
    }
    
    // 检查Java是否可用
    try {
      const javaCmd = javaHome 
        ? path.join(javaHome, 'bin', os.platform() === 'win32' ? 'java.exe' : 'java')
        : 'java';
      
      const javaVersion = execSync(`"${javaCmd}" -version`, { 
        stdio: 'pipe',
        encoding: 'utf8'
      });
      
      if (javaHome) {
        console.log(`✅ Java环境检查通过: ${javaHome}`);
      } else {
        console.log('✅ Java环境检查通过');
      }
      javaFound = true;
    } catch (error) {
      // Java命令执行失败
    }
    
    if (!javaFound) {
      console.warn('⚠️  警告: 未找到Java环境');
      console.warn('   请设置JAVA_HOME环境变量，或确保Android Studio已安装');
      console.warn('   参考文档: docs/JAVA_SETUP.md');
    }
    
  } catch (error) {
    console.warn(`⚠️  环境检查警告: ${error.message}`);
  }
}

// 更新Android配置
function updateAndroidConfig() {
  const androidDir = path.join(__dirname, '..', 'android');
  const appBuildGradlePath = path.join(androidDir, 'app', 'build.gradle');
  
  if (!fs.existsSync(appBuildGradlePath)) {
    console.warn('⚠️  无法找到app/build.gradle，跳过配置更新');
    return;
  }
  
  try {
    let buildGradleContent = fs.readFileSync(appBuildGradlePath, 'utf8');
    
    // 确保 defaultConfig 块存在（防止被意外删除）
    if (!buildGradleContent.includes('defaultConfig')) {
      console.warn('⚠️  检测到 build.gradle 缺少 defaultConfig 块，正在恢复...');
      // 在 signingConfigs 之后、buildTypes 之前插入 defaultConfig
      buildGradleContent = buildGradleContent.replace(
        /(signingConfigs\s*\{[^}]*?\}[^}]*?)(buildTypes)/s,
        `$1\n    defaultConfig {\n        applicationId "${config.appId}"\n        minSdkVersion rootProject.ext.minSdkVersion\n        targetSdkVersion rootProject.ext.targetSdkVersion\n        versionCode ${config.version ? (() => { const m = config.version.match(/^(\d+)\.(\d+)\.(\d+)/); return m ? parseInt(m[1]) * 10000 + parseInt(m[2]) * 100 + parseInt(m[3]) : 10000; })() : 10000}\n        versionName "${config.version || '1.0.0'}"\n        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"\n        aaptOptions {\n             ignoreAssetsPattern '!.svn:!.git:!.ds_store:!*.scc:.*:!CVS:!thumbs.db:!picasa.ini:!*~'\n        }\n    }\n    \n    $2`
      );
      console.log('✅ 已恢复 defaultConfig 块');
    }
    
    // 更新应用ID
    buildGradleContent = buildGradleContent.replace(
      /applicationId\s+["'][^"']+["']/,
      `applicationId "${config.appId}"`
    );
    
    // 更新版本号（如果配置中有）
    if (config.version) {
      const versionMatch = config.version.match(/^(\d+)\.(\d+)\.(\d+)/);
      if (versionMatch) {
        const [, major, minor, patch] = versionMatch;
        buildGradleContent = buildGradleContent.replace(
          /versionCode\s+\d+/,
          `versionCode ${parseInt(major) * 10000 + parseInt(minor) * 100 + parseInt(patch)}`
        );
        buildGradleContent = buildGradleContent.replace(
          /versionName\s+["'][^"']+["']/,
          `versionName "${config.version}"`
        );
      }
    }
    
    // 更新minSdkVersion（支持 rootProject.ext.minSdkVersion 格式）
    if (config.android.minSdkVersion) {
      // 先尝试替换 rootProject.ext.minSdkVersion 格式
      if (buildGradleContent.includes('rootProject.ext.minSdkVersion')) {
        // 更新 variables.gradle 文件
        const variablesGradlePath = path.join(androidDir, 'variables.gradle');
        if (fs.existsSync(variablesGradlePath)) {
          let variablesContent = fs.readFileSync(variablesGradlePath, 'utf8');
          variablesContent = variablesContent.replace(
            /minSdkVersion\s*=\s*\d+/,
            `minSdkVersion = ${config.android.minSdkVersion}`
          );
          fs.writeFileSync(variablesGradlePath, variablesContent);
          console.log(`✅ 已更新 variables.gradle: minSdkVersion = ${config.android.minSdkVersion}`);
        }
      } else {
        // 如果使用直接数值，则替换
        buildGradleContent = buildGradleContent.replace(
          /minSdkVersion\s+\d+/,
          `minSdkVersion ${config.android.minSdkVersion}`
        );
      }
    }
    
    // 更新targetSdkVersion（支持 rootProject.ext.targetSdkVersion 格式）
    if (config.android.targetSdkVersion) {
      // 先尝试替换 rootProject.ext.targetSdkVersion 格式
      if (buildGradleContent.includes('rootProject.ext.targetSdkVersion')) {
        // 更新 variables.gradle 文件
        const variablesGradlePath = path.join(androidDir, 'variables.gradle');
        if (fs.existsSync(variablesGradlePath)) {
          let variablesContent = fs.readFileSync(variablesGradlePath, 'utf8');
          variablesContent = variablesContent.replace(
            /targetSdkVersion\s*=\s*\d+/,
            `targetSdkVersion = ${config.android.targetSdkVersion}`
          );
          fs.writeFileSync(variablesGradlePath, variablesContent);
          console.log(`✅ 已更新 variables.gradle: targetSdkVersion = ${config.android.targetSdkVersion}`);
        }
      } else {
        // 如果使用直接数值，则替换
        buildGradleContent = buildGradleContent.replace(
          /targetSdkVersion\s+\d+/,
          `targetSdkVersion ${config.android.targetSdkVersion}`
        );
      }
    }
    
    // 更新compileSdkVersion（支持 rootProject.ext.compileSdkVersion 格式）
    if (config.android.compileSdkVersion) {
      if (buildGradleContent.includes('rootProject.ext.compileSdkVersion')) {
        const variablesGradlePath = path.join(androidDir, 'variables.gradle');
        if (fs.existsSync(variablesGradlePath)) {
          let variablesContent = fs.readFileSync(variablesGradlePath, 'utf8');
          variablesContent = variablesContent.replace(
            /compileSdkVersion\s*=\s*\d+/,
            `compileSdkVersion = ${config.android.compileSdkVersion}`
          );
          fs.writeFileSync(variablesGradlePath, variablesContent);
          console.log(`✅ 已更新 variables.gradle: compileSdkVersion = ${config.android.compileSdkVersion}`);
        }
      }
    }
    
    // 配置签名（如果启用）
    if (config.signing && config.signing.enabled && config.buildMode === 'release') {
      const keystorePath = path.resolve(__dirname, '..', config.signing.keystorePath);
      
      if (!fs.existsSync(keystorePath)) {
        throw new Error(`Keystore文件不存在: ${keystorePath}`);
      }
      
      // 检查是否已有signingConfigs配置
      if (!buildGradleContent.includes('signingConfigs')) {
        // 在android块中添加signingConfigs
        buildGradleContent = buildGradleContent.replace(
          /(android\s*\{[^}]*)(defaultConfig)/,
          `$1\n    signingConfigs {\n        release {\n            storeFile file('${path.relative(path.dirname(appBuildGradlePath), keystorePath).replace(/\\/g, '/')}')\n            storePassword '${config.signing.keystorePassword}'\n            keyAlias '${config.signing.keyAlias}'\n            keyPassword '${config.signing.keyPassword}'\n        }\n    }\n    $2`
        );
      } else {
        // 更新现有的signingConfigs - 使用更精确的匹配，避免破坏文件结构
        // 注意：不再清理大括号，因为这可能会误删 defaultConfig 块的关闭大括号
        // 如果文件结构有问题，会在后续的验证和修复步骤中处理
        
        // 匹配整个signingConfigs块（包括嵌套的release块）
        // 使用非贪婪匹配，确保只匹配到signingConfigs块的结束，不包含 defaultConfig
        // 匹配 signingConfigs { ... } 后面跟着空白和 defaultConfig 或 buildTypes
        const signingConfigsPattern = /(signingConfigs\s*\{[^}]*?release\s*\{[^}]*?\}[^}]*?\})(\s*(?:defaultConfig|buildTypes))/s;
        
        if (signingConfigsPattern.test(buildGradleContent)) {
          const newSigningConfigs = `signingConfigs {\n        release {\n            storeFile file('${path.relative(path.dirname(appBuildGradlePath), keystorePath).replace(/\\/g, '/')}')\n            storePassword '${config.signing.keystorePassword}'\n            keyAlias '${config.signing.keyAlias}'\n            keyPassword '${config.signing.keyPassword}'\n        }\n    }`;
          // 使用捕获组保留后面的 defaultConfig 或 buildTypes
          buildGradleContent = buildGradleContent.replace(signingConfigsPattern, `${newSigningConfigs}$2`);
        } else {
          console.warn('⚠️  无法匹配现有的signingConfigs配置，跳过更新');
        }
      }
      
      // 在release buildType中应用签名配置
      if (buildGradleContent.includes('buildTypes')) {
        if (!buildGradleContent.includes('signingConfig signingConfigs.release')) {
          buildGradleContent = buildGradleContent.replace(
            /(release\s*\{[^}]*)(minifyEnabled)/,
            `$1            signingConfig signingConfigs.release\n            $2`
          );
        }
      }
      
      console.log('✅ 签名配置已添加到build.gradle');
    }
    
    // 签名配置更新后，再次确保 defaultConfig 块存在（防止被签名配置更新逻辑破坏）
    if (!buildGradleContent.includes('defaultConfig')) {
      console.warn('⚠️  签名配置更新后检测到 defaultConfig 块缺失，正在恢复...');
      if (buildGradleContent.includes('signingConfigs') && buildGradleContent.includes('buildTypes')) {
        buildGradleContent = buildGradleContent.replace(
          /(signingConfigs\s*\{[^}]*?\}[^}]*?)(buildTypes)/s,
          `$1\n    defaultConfig {\n        applicationId "${config.appId}"\n        minSdkVersion rootProject.ext.minSdkVersion\n        targetSdkVersion rootProject.ext.targetSdkVersion\n        versionCode ${config.version ? (() => { const m = config.version.match(/^(\d+)\.(\d+)\.(\d+)/); return m ? parseInt(m[1]) * 10000 + parseInt(m[2]) * 100 + parseInt(m[3]) : 10000; })() : 10000}\n        versionName "${config.version || '1.0.0'}"\n        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"\n        aaptOptions {\n             ignoreAssetsPattern '!.svn:!.git:!.ds_store:!*.scc:.*:!CVS:!thumbs.db:!picasa.ini:!*~'\n        }\n    }\n    \n    $2`
        );
        console.log('✅ 已恢复 defaultConfig 块');
      }
    }
    
    // 验证 defaultConfig 块是否完整（包含开始和结束大括号）
    const defaultConfigMatch = buildGradleContent.match(/defaultConfig\s*\{[^}]*\}/s);
    const hasCompleteDefaultConfig = defaultConfigMatch !== null;
    
    if (!hasCompleteDefaultConfig && buildGradleContent.includes('defaultConfig')) {
      console.warn('⚠️  检测到 defaultConfig 块不完整，尝试修复...');
      // 尝试修复：在 defaultConfig 块的 aaptOptions 后添加关闭大括号
      buildGradleContent = buildGradleContent.replace(
        /(aaptOptions\s*\{[^}]*ignoreAssetsPattern[^}]*\})\s*(buildTypes)/s,
        `$1\n        }\n    }\n    \n    $2`
      );
    }
    
    fs.writeFileSync(appBuildGradlePath, buildGradleContent);
    console.log('✅ Android build.gradle配置已更新');
    
    // 更新应用名称（strings.xml）
    updateAppName();
  } catch (error) {
    console.warn(`⚠️  更新Android配置失败: ${error.message}`);
  }
}

// 更新Android应用名称
function updateAppName() {
  const androidDir = path.join(__dirname, '..', 'android');
  const stringsXmlPath = path.join(androidDir, 'app', 'src', 'main', 'res', 'values', 'strings.xml');
  
  if (!fs.existsSync(stringsXmlPath)) {
    console.warn('⚠️  无法找到strings.xml，跳过应用名称更新');
    return;
  }
  
  try {
    let stringsXmlContent = fs.readFileSync(stringsXmlPath, 'utf8');
    
    // 更新app_name
    stringsXmlContent = stringsXmlContent.replace(
      /<string name="app_name">[^<]+<\/string>/,
      `<string name="app_name">${config.appName}</string>`
    );
    
    // 更新title_activity_main
    stringsXmlContent = stringsXmlContent.replace(
      /<string name="title_activity_main">[^<]+<\/string>/,
      `<string name="title_activity_main">${config.appName}</string>`
    );
    
    // 更新package_name（如果需要）
    if (config.appId) {
      stringsXmlContent = stringsXmlContent.replace(
        /<string name="package_name">[^<]+<\/string>/,
        `<string name="package_name">${config.appId}</string>`
      );
      
      // 更新custom_url_scheme
      stringsXmlContent = stringsXmlContent.replace(
        /<string name="custom_url_scheme">[^<]+<\/string>/,
        `<string name="custom_url_scheme">${config.appId}</string>`
      );
    }
    
    fs.writeFileSync(stringsXmlPath, stringsXmlContent);
    console.log(`✅ Android应用名称已更新: ${config.appName}`);
  } catch (error) {
    console.warn(`⚠️  更新应用名称失败: ${error.message}`);
  }
}

// 执行Gradle构建
function buildAPK() {
  const androidDir = path.join(__dirname, '..', 'android');
  const buildType = config.buildMode === 'release' ? 'release' : 'debug';
  const gradleCmd = getGradleCommand();
  
  console.log(`🔨 执行Gradle构建 (${buildType})...`);
  console.log(`   平台: ${os.platform()}`);
  console.log(`   Gradle命令: ${gradleCmd}`);
  
  // 检查并修复 gradlew 执行权限（macOS/Linux）
  if (os.platform() !== 'win32' && gradleCmd === './gradlew') {
    const gradlewPath = path.join(androidDir, 'gradlew');
    if (fs.existsSync(gradlewPath)) {
      try {
        const stats = fs.statSync(gradlewPath);
        // 检查是否有执行权限（检查 owner execute bit）
        const mode = stats.mode;
        const executeBit = 0o111; // 执行权限位
        if ((mode & executeBit) === 0) {
          console.log('🔧 检测到 gradlew 缺少执行权限，正在修复...');
          fs.chmodSync(gradlewPath, '755'); // 添加执行权限: rwxr-xr-x
          console.log('✅ 已修复 gradlew 执行权限');
        }
      } catch (error) {
        console.warn(`⚠️  无法检查 gradlew 权限: ${error.message}`);
      }
    }
  }
  
  try {
    // 清理之前的构建
    console.log('🧹 清理之前的构建...');
    execSync(`${gradleCmd} clean`, {
      stdio: 'inherit',
      cwd: androidDir,
      shell: os.platform() === 'win32' // Windows需要shell
    });
    
    // 构建APK
    const buildCommand = buildType === 'release' 
      ? `${gradleCmd} assembleRelease` 
      : `${gradleCmd} assembleDebug`;
    
    console.log(`📦 执行构建命令: ${buildCommand}`);
    execSync(buildCommand, {
      stdio: 'inherit',
      cwd: androidDir,
      shell: os.platform() === 'win32' // Windows需要shell
    });
    
    console.log(`✅ Gradle构建完成 (${buildType})`);
    
  } catch (error) {
    throw new Error(`Gradle构建失败: ${error.message}`);
  }
}

// 复制APK到输出目录
function copyAPK() {
  const androidDir = path.join(__dirname, '..', 'android');
  const buildType = config.buildMode === 'release' ? 'release' : 'debug';
  const apkSourceDir = path.join(
    androidDir, 
    'app', 
    'build', 
    'outputs', 
    'apk', 
    buildType
  );
  
  if (!fs.existsSync(apkSourceDir)) {
    throw new Error(`APK输出目录不存在: ${apkSourceDir}`);
  }
  
  const apkFiles = fs.readdirSync(apkSourceDir).filter(file => file.endsWith('.apk'));
  if (apkFiles.length === 0) {
    throw new Error('未找到APK文件');
  }
  
  // 创建输出目录
  const outputDir = path.join(__dirname, '..', config.outputDir);
  if (!fs.existsSync(outputDir)) {
    fs.mkdirSync(outputDir, { recursive: true });
  }
  
  // 复制APK文件
  apkFiles.forEach(apkFile => {
    const sourcePath = path.join(apkSourceDir, apkFile);
    const destPath = path.join(outputDir, apkFile);
    
    fs.copyFileSync(sourcePath, destPath);
    console.log(`✅ 复制APK: ${apkFile}`);
    
    // 显示文件大小
    const stats = fs.statSync(destPath);
    const sizeInMB = (stats.size / 1024 / 1024).toFixed(2);
    console.log(`   文件大小: ${sizeInMB} MB`);
  });
  
  console.log(`\n✅ APK文件已复制到: ${config.outputDir}`);
}

// 主函数
function main() {
  try {
    validateAndroidProject();
    checkAndroidSDK();
    configureLocalProperties(); // 配置local.properties
    updateAndroidConfig();
    buildAPK();
    copyAPK();
    
    console.log('\n✅ APK编译流程完成！');
    console.log(`\n📦 APK文件位置: ${path.join(__dirname, '..', config.outputDir)}`);
  } catch (error) {
    console.error('\n❌ 编译失败:', error.message);
    console.error('\n提示:');
    console.error('1. 确保已安装Android SDK和Android Studio');
    console.error('2. 确保已设置ANDROID_HOME环境变量');
    console.error('3. 确保已安装JDK 11+');
    console.error('4. 如果是Release版本，请配置签名信息');
    process.exit(1);
  }
}

main();

